### ISSUE TITLE
Msg package pattern

### ISSUE THREAD

**Issue by FlyingBobino** [Simba-Avionic/gs_interfaces#2]
Aktualnie uporządkowałem wiadomości po "klasach" (tanking_msgs, radio_msgs itd.) za pomocą wrzucania ich do poszczególnych folderów - powinno działać, ale raczej z tego co widziałem to konsensus jest żeby każda "klasa" była osobną paczką

**Comment by mmatuszewsky** [comment]
myślę, że dla naszych celów powinno być ok
